service: cloud-music-backend

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  environment:
    USER_POOL_ID: eu-central-1_AHb0aoBcX
    CLIENT_ID: 7gvfvp342fp6i6bdtsjrgl6a47

functions:
  register:
    handler: handler.register
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  login:
    handler: handler.login
    events:
      - http:
          path: auth/login
          method: post
          cors: true

plugins:
  - serverless-python-requirements

resources:
  Resources:
    MusicContentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MusicContent
        AttributeDefinitions:
          - AttributeName: genre
            AttributeType: S
          - AttributeName: contentId
            AttributeType: S
        KeySchema:
          - AttributeName: genre
            KeyType: HASH
          - AttributeName: contentId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

custom:
  pythonRequirements:
    dockerizePip: true