service: cloud-music-backend

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  environment:
    USER_POOL_ID: eu-central-1_AHb0aoBcX
    CLIENT_ID: 7gvfvp342fp6i6bdtsjrgl6a47

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource:
        - "arn:aws:dynamodb:eu-central-1:*:table/Artists"

        
functions:
  register:
    handler: handler.register
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  login:
    handler: handler.login
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  createArtist:
    handler: handler.create_artist
    events:
      - http:
          path: admin/artist
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:eu-central-1:605454152564:userpool/eu-central-1_AHb0aoBcX


resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ArtistsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Artists
        AttributeDefinitions:
          - AttributeName: artistId
            AttributeType: S
        KeySchema:
          - AttributeName: artistId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true